server:
  port: 9527

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skylark_permission?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: dev
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false

oauth:
  signingKey: 374SJADK&*@!SHSAshhsdevops(90)

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.skylark.permission.oauth2.entity
  configuration:
    map-underscore-to-camel-case: true

jackson:
  serialization:
    write-dates-as-timestamps: false
  deserialization:
    fail-on-unknown-properties: false